### ISSUE TITLE
Infinite Loop on new YoloWrapper

### ISSUE THREAD

**Issue by StefanCiobanu1989** [12343954/Darknet.YoloV3#1]
Hi, for some reason the application starts but nothing happens, the button has the spinning animation but it never stops for some reason the YOLO object is always null resulting in "YOLO not init ..." when the button is clicked
I have tried placing a breakpoint on Form1.cs line 54 however when i try to STEP IN i cant because the file does not exist. Some assistance would mean a lot ! Thanks !

**Comment by StefanCiobanu1989** [comment]
if i was to remove the GpuConfig from YoloWrapper from 
  ```
YOLO = new YoloWrapper(GG.YOLOv3.ConfigFile,
                                    GG.YOLOv3.WeightsFile,
                                    GG.YOLOv3.NamesFile,
                                    GpuConfig);
```
everything works however the fps drops to 2 since gpu is not being used however gpu is kinda of a critical factor which is not working. i'll keep on looking . 

After some more investigations it turns out the following is preventing functionality : 
 "Unable to load DLL 'yolo_cpp_dll_gpu': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"

The method that triggers this is : Alturos.Yolo.YoloWrapper.GetDeviceCount(). It seems i'm damned, no matter what version of cuda/cudnn this does not go away. Please let me know if

**Comment by 12343954** [comment]
You must correctly install and configure the CUDA、OpenCV  etc. in Environment Variables. 
Please refer to this, https://youtu.be/zT8eDXpslXw, or https://github.com/AlexeyAB/darknet
